.PHONY: task1 task2 task3 task4 task5 clean

task1:
	$(MAKE) -C task1

task1.solution:
	$(MAKE) -C task1 solution

task1.profile:
	$(MAKE) -C task1 profile

task2:
	$(MAKE) -C task2

task2.solution:
	$(MAKE) -C task2 solution

task2.profile:
	$(MAKE) -C task2 profile 

task3:
	$(MAKE) -C task3

task3.solution:
	$(MAKE) -C task3 solution

task3.profile:
	$(MAKE) -C task3 profile

task4:
	$(MAKE) -C task4

task4.solution:
	$(MAKE) -C task4 solution

task4.profile:
	$(MAKE) -C task4 profile

task5:
	$(MAKE) -C task5

task5.solution:
	$(MAKE) -C task5 solution

task5.profile:
	$(MAKE) -C task5 profile

clean:
	$(MAKE) -C task1 clean
	$(MAKE) -C task2 clean
	$(MAKE) -C task3 clean
	$(MAKE) -C task4 clean
	$(MAKE) -C task5 clean
